### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by dtordable** [collective/collective.googleanalytics#23]
I've installed c.googleanalytics before and it worked already but this time I installed the productos and failed on the authorisation. So it didn'r worked. Any clue?

**Comment by dtordable** [comment]
I have investigated the case. Google change

**Comment by dtordable** [comment]
Changes from oauth1 to oauth2 so this product needs to be modified.

**Comment by macagua** [comment]
@dtordable I have the same error :+1: I agree with you, that error should be!!!

**Comment by luketunmer** [comment]
I use this plugin all the time on all of my plone sites. Any idea of if and when this will be fixed? I see that there is an oauth2 branch, but no indication of the progress down that path. If help is needed, then let us know.

**Comment by dtordable** [comment]
Trying to solve this with the oauth2 branch. Got a live site working.
