### ISSUE TITLE
Will be broken for Plone 5

### ISSUE THREAD

**Issue by dtordable** [collective/collective.googleanalytics#24]
Tried to upgrade to Plone 5.0rc3 and having this egg in the buildout makes the instance to crash because recent changes to Plone the system.  Keep an eye into it, because Plone deserves this add-on.

**Comment by tomgross** [comment]
@dtordable Can you Elaborate what exactly your issue is on Plone 5? This makes it easier to fix for other People.

**Comment by dtordable** [comment]
Seen some upgrade guide not completed and says something like "from" text and upgrading to rc3 failed in fg mode because because of this addon

**Comment by danmur** [comment]
Here's a traceback: https://bitbucket.org/snippets/danmur/R8K8M

Looks like this import in collective/googleanalytics/browser/controlpanel.py:
from plone.app.controlpanel.form import ControlPanelForm

Possibly related to this: https://dev.plone.org/ticket/10359 ?

**Comment by davisagli** [comment]
Yes, it needs to be updated to use a z3c.form-based control panel.

**Comment by neilferreira** [comment]
I was having a quick shot at updating this to use z3c.form, unfortunately the entire addon no longer works as Google have deprecated the OAuth API that is still being used. 

FYI my work has been checked in here: https://github.com/neilferreira/collective.googleanalytics/commit/d40dfd96b430b60311f2274a18a278599b3b4a16

**Comment by tomgross** [comment]
The addon is no tested on Plone 5 and 5.1
